---
title: "case study"
author: "Huili Zheng"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
library(p8105.datasets)
```

## load the dataset

```{r}
data(nyc_airbnb)
```



```{r}
nyc_airbnb <-
  nyc_airbnb %>%
  mutate(
    stars = review_scores_location / 2
  ) %>%
  rename(
    borough = neighbourhood_group
  )
```

Lets try count things. 

how many rentals are there? of what type? in what places?
```{r}
nyc_airbnb %>%
  count(borough, room_type) %>%
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```


is price correlated with the review score?
look at price and room type
```{r}
nyc_airbnb %>%
  ggplot(aes(x = stars, y = price)) +
  geom_point()
```


```{r}

nyc_airbnb %>%
  filter(borough == "Manhattan") %>%
  group_by(neighbourhood) %>%
  summarize(mean_price = mean(price, na.rm = TRUE)) %>%
  arrange(mean_price)



nyc_airbnb %>%
  filter(borough == "Manhattan",
         price <= 1000) %>%
  mutate(neighbourhood = 
           fct_reorder(neighbourhood, price)) %>%
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(. ~room_type)
``` 


price vs location

```{r}

nyc_airbnb %>%
  filter(price < 500 ) %>%
  sample_n(5000) %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(aplha = .3)
```

## retry leaflet

```{r, evale = FALSE}  

pal = colorNumeric("viridis",NULL)

nyc_airbnb %>%
  mutate(
    labels = str_c("<b>Price:",price,"</b><br>Stars:",stars)
  ) %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  ##check for leaflet for R
  addCircleMarkers(~lat, ~long, radius = 1, color = ~pal(price), popup = ~labels)

nyc_airbnb %>%  
  filter(price < 500) %>%
  sample_n(1000) %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  ##check for leaflet for R
  #addTiles() %>%
  #addMarkers(~lat, ~long)
  addCircleMarkers(~lat, ~long, radius = 1, color = ~pal(price))

```











